---
name: Build and Push Container Image
on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md' # Don't trigger builds for documentation changes
  workflow_dispatch:
    inputs: {}

permissions:
  contents: read
  packages: write

env:
  version: "27.1"

jobs:
  build:
    name: Build and Push Container Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        id: launch_builder

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Image
        run: |
          TIMESTAMP=$(date --utc +%Y-%m-%dT%H%M%S)

          docker buildx use ${{ steps.launch_builder.outputs.name }}
          docker buildx build --push --pull\
            --platform linux/amd64,linux/arm64\
            --build-arg VERSION=${{ env.version }}\
            --label "org.label-schema.vcs-ref=${{ github.sha }}"\
            --label "org.label-schema.version=${{ env.version }}"\
            --tag ghcr.io/jmanero/fulcrum:latest\
            --tag ghcr.io/jmanero/fulcrum:${{ env.version }}\
            --tag ghcr.io/jmanero/fulcrum:${{ env.version }}-${{ github.sha }}\
            --file Containerfile .
